#include <stdio.h>

#include <kernel/tty.h>

void kernel_main(void) {
	terminal_initialize();
	printf("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel dictum urna, non venenatis urna. Praesent maximus enim vel tortor faucibus, eu fermentum diam euismod. Duis eget nisl pretium, lobortis lacus sed, mattis sapien. Suspendisse quis diam et massa pellentesque pellentesque nec quis risus. Sed pharetra mollis varius. Nunc viverra est quis est rutrum ullamcorper. Vivamus non erat hendrerit, ultrices turpis eget, porttitor lorem. Praesent arcu nisl, venenatis nec quam vel, placerat posuere enim. In ut diam dolor. Morbi dictum nulla eget mi lobortis varius.\n");
	printf("Nulla tincidunt efficitur cursus. Maecenas scelerisque non diam nec posuere. Fusce vulputate risus convallis tristique consectetur. Cras porttitor, mi non lobortis fermentum, ante erat eleifend sem, sodales molestie lorem odio sit amet magna. Nullam vestibulum diam orci, sit amet sollicitudin orci fringilla non. Nam sit amet quam at risus rhoncus commodo. Suspendisse eu est venenatis, gravida odio vel, rhoncus risus.\n");
	printf("Aenean maximus neque eros, a efficitur dui hendrerit faucibus. Nullam ut felis in felis consectetur vehicula quis sed ante. Nullam quis semper tellus. Aliquam laoreet non ante in imperdiet. Nulla ut finibus dui, tristique accumsan nisl. Etiam a massa in enim blandit placerat. Praesent sed convallis quam, eget tristique magna. Donec ac ante sed velit rutrum gravida. Sed dapibus non velit non lacinia. Morbi eleifend vulputate quam varius faucibus. Aliquam id ipsum dignissim, varius ipsum a, elementum quam. Phasellus id velit est. Suspendisse pellentesque risus nec maximus commodo. Vestibulum porttitor eu lorem vitae vestibulum.\n");
	printf("Proin orci ligula, porta sed rhoncus a, interdum in dolor. Pellentesque eleifend, massa et ullamcorper tincidunt, erat sapien hendrerit risus, id sagittis lectus risus vel orci. Pellentesque ut suscipit eros. Phasellus pulvinar maximus tortor, id feugiat magna eleifend laoreet. Nam sit amet metus et diam tempor imperdiet sit amet eget augue. Aliquam tincidunt ipsum augue, nec porta ex tristique non. Maecenas viverra urna feugiat sem condimentum, fringilla accumsan nulla lobortis. Cras vel fermentum nunc, a dignissim nulla. Ut pulvinar finibus velit, et hendrerit magna molestie id. Nulla fermentum gravida augue, eget lobortis nunc pulvinar consectetur. Sed volutpat vestibulum ante eu sodales. Sed felis lectus, condimentum condimentum est a, fermentum imperdiet elit. Sed malesuada tristique dignissim. Nulla id orci non risus vulputate mattis. Fusce sodales molestie gravida.\n");
/*
Sed euismod eleifend varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur facilisis ullamcorper felis, eu sagittis enim ullamcorper sed. Donec id velit vel ex cursus dictum iaculis nec tortor. Suspendisse rutrum elementum tortor, id faucibus tellus gravida sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce mollis massa nec mi semper pharetra. Nulla nulla purus, vehicula non leo eu, bibendum sollicitudin justo. Suspendisse porttitor odio metus, eu consectetur neque commodo ut. Pellentesque gravida fringilla cursus. Donec dictum, tortor non mattis aliquam, justo nunc finibus odio, in imperdiet tellus leo non mi. Donec erat urna, ultrices dictum nunc sagittis, interdum efficitur ante. Morbi congue lorem at sem iaculis, nec tristique dui dignissim. Vivamus quis leo quis magna ultrices elementum. Donec vulputate auctor dolor, ut dignissim mauris pretium a.
*/
}
